"""add questions table

Revision ID: add_questions_table
Revises: 3670f8aef675
Create Date: 2024-01-XX XX:XX:XX.XXXXXX

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_questions_table"
down_revision = "b5feba8e4925"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("option_a", sa.String(length=500), nullable=True),
        sa.Column("option_b", sa.String(length=500), nullable=True),
        sa.Column("option_c", sa.String(length=500), nullable=True),
        sa.Column("option_d", sa.String(length=500), nullable=True),
        sa.Column("correct_answer", sa.String(length=1), nullable=True),
        sa.Column("order_num", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_exam_id"), ["exam_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_order_num"), ["order_num"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_order_num"))
        batch_op.drop_index(batch_op.f("ix_questions_exam_id"))

    op.drop_table("questions")
    # ### end Alembic commands ###
